spring.application.name=moduplan

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/moduplan?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=your-very-secret-key-your-very-secret-key
jwt.access-expiration=3600000
jwt.refresh-expiration=604800000

spring.data.redis.host=darling-grubworm-75816.upstash.io
spring.data.redis.port=6379
spring.data.redis.password=gQAAAAAAASgoAAIncDExNWRlODdlYzhlYWI0MDFkOWMxNTU1ZGExMDRlY2QwMHAxNzU4MTY
spring.data.redis.ssl.enabled=true