spring.application.name=moduplan
server.port=8081

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/moduplan?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=your-very-secret-key-your-very-secret-key
jwt.access-expiration=3600000
jwt.refresh-expiration=604800000

spring.data.redis.host=darling-grubworm-75816.upstash.io
spring.data.redis.port=6379
spring.data.redis.password=gQAAAAAAASgoAAIncDExNWRlODdlYzhlYWI0MDFkOWMxNTU1ZGExMDRlY2QwMHAxNzU4MTY
spring.data.redis.ssl.enabled=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.security.oauth2.client.registration.kakao.client-id=b2c51fc7cc192d520255188b2e54baaf
spring.security.oauth2.client.registration.kakao.client-authentication-method=none
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.kakao.redirect-uri=http://localhost:8081/login/oauth2/code/kakao
spring.security.oauth2.client.registration.kakao.scope=profile_nickname
spring.security.oauth2.client.registration.kakao.client-name=Kakao

spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id
