spring.application.name=moduplan
spring.profiles.default=local

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
