name: CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    env:
      SPRING_APPLICATION_NAME: ${{ vars.SPRING_APPLICATION_NAME }}
      SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
      SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${{ vars.SPRING_JPA_HIBERNATE_DDL_AUTO }}
      SPRING_JPA_SHOW_SQL: ${{ vars.SPRING_JPA_SHOW_SQL }}
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: ${{ vars.SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_ACCESS_EXPIRATION: ${{ vars.JWT_ACCESS_EXPIRATION }}
      JWT_REFRESH_EXPIRATION: ${{ vars.JWT_REFRESH_EXPIRATION }}
      SPRING_DATA_REDIS_HOST: ${{ secrets.SPRING_DATA_REDIS_HOST }}
      SPRING_DATA_REDIS_PORT: ${{ secrets.SPRING_DATA_REDIS_PORT }}
      SPRING_DATA_REDIS_PASSWORD: ${{ secrets.SPRING_DATA_REDIS_PASSWORD }}
      SPRING_DATA_REDIS_SSL_ENABLED: ${{ vars.SPRING_DATA_REDIS_SSL_ENABLED }}
      SPRINGDOC_API_DOCS_PATH: ${{ vars.SPRINGDOC_API_DOCS_PATH }}
      SPRINGDOC_SWAGGER_UI_PATH: ${{ vars.SPRINGDOC_SWAGGER_UI_PATH }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Grant gradlew execute permission
        run: chmod +x gradlew

      - name: Build and test
        run: ./gradlew clean build
